apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
spec:
  project: guestbook
  source:
    repoURL: 'https://github.com/crazylearning-cr/argo-multi-cluster-deployments.git'
    targetRevision: main
    path: kustomize/overlays/dev
  destination:
    server: https://26FCF9DA4ACDE97CFFA0688F62D86021.gr7.us-east-1.eks.amazonaws.com
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
spec:
  project: guestbook
  source:
    repoURL: 'https://github.com/crazylearning-cr/argo-multi-cluster-deployments.git'
    targetRevision: main
    path: kustomize/overlays/prod
  destination:
    server: https://D25809CD9BA2111831BEEE33CFFEB9AF.gr7.ap-south-1.eks.amazonaws.com
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
